### ISSUE TITLE
mira user is not searchable

### ISSUE THREAD

**Issue by pandafliesinspace** [holypower777/global-chat#2]
**Describe the bug**
input 'mira' user nickname in search textfield

**To Reproduce**
1. Go to 'https://twitch-global-chat.herokuapp.com/'
2. Click on 'input 'mira' nickname to search textfield'
3. press enter

**Screenshots**
![image](https://user-images.githubusercontent.com/26408366/166447918-24d44469-1a50-485f-900c-9bafb81b95c0.png)

**Device details**
 - OS: Windows 10(stolen)
 - Browser [e.g. chrome, safari] Microsoft Edge 
 - Browser Version [e.g. 22] Версия 101.0.1210.32 (Официальная сборка) (64-разрядная версия)

**Additional context**
хочу миру

**Comment by pandafliesinspace** [comment]
Please review and fix ASAP

**Comment by pandafliesinspace** [comment]
This user is also cannot be accessed [via url](https://twitch-global-chat.herokuapp.com/messages/mira)

**Comment by pandafliesinspace** [comment]
@holypower777 any update?

**Comment by pandafliesinspace** [comment]
Also reproduces with 'tati' user nickname

**Comment by holypower777** [comment]
work in progress
![work in progress](https://media4.giphy.com/media/l0K4hO8mVvq8Oygjm/giphy.gif?cid=ecf05e47aojjcn8e1660hgiwuu5dvfifd890u48fejogje08&rid=giphy.gif&ct=g)

**Comment by pandafliesinspace** [comment]
@holypower777  any fix ETA?

**Comment by holypower777** [comment]
> @holypower777 any fix ETA?

roughly 3 hours

**Comment by Nestert** [comment]
cannot wait fix

**Comment by pandafliesinspace** [comment]
@holypower777 
![image](https://user-images.githubusercontent.com/26408366/166477619-79b8b72f-cd5e-479d-b0e3-45d614b3b764.png)
