### ISSUE TITLE
Сайт не открывается

### ISSUE THREAD

**Issue by cyperdark** [holypower777/global-chat#41]
![chrome_phTwCKkGTQ](https://user-images.githubusercontent.com/21735205/193502144-27c97ed3-5bf9-42ed-94ad-a470dd2f735c.png)

**Comment by pandafliesinspace** [comment]
@holypower777 any update?

**Comment by holypower777** [comment]
> @holypower777 when we see any update?



> @holypower777 any update?

https://youtu.be/l_KEXiybrWw?t=92
